version: '3.8'

services:
  code-server:
    image: codercom/code-server:latest
    container_name: code-server
    ports:
      - "4000:8080" # Bind to localhost for code-server
    volumes:
      - "$HOME/.config:/home/coder/.config" # User configuration
      - ../FASTAPI:/home/coder/project # Path to your FastAPI project
    environment:
      - DOCKER_USER=${USER} # Pass current user
      - PASSWORD=${PASSWORD} # Set a password for access
    user: "${UID}:${GID}" # Run as current user
    networks:
      - app-network

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "9000:9000" # Bind to localhost for Portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Access Docker daemon
      - portainer_data:/data # Persist Portainer data
    networks:
      - app-network

networks:
  app-network:

volumes:
  portainer_data:
